#%RAML 1.0 Trait

usage: Adds client id and client secret headers.Alternative structure for Anypoint's Client ID Enforcement authentication policy.
headers:
      client_id:
        type: string
        required: true
      client_secret:
        type: string
        required: true