#%RAML 1.0 NamedExample
name:
  success: false
  httpStatusCode: 400
  application: <<resourcePath>>
  transactionId: 7cc64d24-f2ad-4d43-8893-fa24a0789a99
  transactionType: placeholder
  exceptionDetails:
    exceptionCode: placeholder
    exceptionTimestamp: 2018-07-19T10:20:11.843Z
    exceptionMessage: placeholder
    description: placeholder