#%RAML 1.0 DataType
type: string
description: A UUID (universal unique identifier).
minLength: 36
maxLength: 36
pattern: '(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}'
example: 7cc64d24-f2ad-4d43-8893-fa24a0789a99